[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "@setToken/contracts=src/set-tokens-v2/"]

# [rpc_endpoints]
# SEPOLIA_URL = "${SEPOLIA_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
